### ISSUE TITLE
Question about OpenEXR

### ISSUE THREAD

**Issue by mworchel** [BachiLi/redner-dependencies#1]
There seems to be some history of deleting and reviving OpenEXR as dependency but I couldn't find any reference to it in the C++ source code. What is it currently used for? 

The context is that I'm working on Windows compatibility as stated in https://github.com/BachiLi/redner/issues/7 and OpenEXR caused some trouble when building the Python wheels.

**Comment by BachiLi** [comment]
It is not used in the C++ code. It is used here: https://github.com/BachiLi/redner/blob/master/pyredner/image.py which depends on the openexrpython package https://github.com/jamesbowman/openexrpython which depends on OpenEXR.
(Thanks a lot for the efforts btw!)

**Comment by mworchel** [comment]
I'm not so familiar with all the python bindings and packages stuff but couldn't you just list OpenEXR as requirement for your python package (as similarly done with `scikit-image`)? There is a pip package for OpenEXR (https://pypi.org/project/OpenEXR) so one could rely on that. Although `pip install OpenEXR` doesn't work on Win32, one can get the inofficial package from https://www.lfd.uci.edu/~gohlke/pythonlibs/ and `pip install` it.

I find differentiable rendering and its applications to be a very interesting research topic. I'll gladly help you reach more people. ... And I'm working under Windows, so I also benefit from the efforts :)

**Comment by BachiLi** [comment]
Unfortunately this wouldn't work -- OpenEXR and openexrpython are two different systems and openexrpython assumes OpenEXR (which is a C++ library) is already installed in the system if you `pip install openexrpython`.  What exactly is the problem when installing OpenEXR in windows?

**Comment by mworchel** [comment]
> What exactly is the problem when installing OpenEXR in windows?

I didn't really dive deep into why it didn't compile. I was just wondering why we would need to build it ourselves.

> Unfortunately this wouldn't work -- OpenEXR and openexrpython are two different systems and openexrpython assumes OpenEXR (which is a C++ library) is already installed in the system if you pip install openexrpython.

I just tried `pip install OpenEXR` (note, it's not `openexrpython`) and that works fine. I can run an example using the `image.py` file and write an `exr` image without explicitely installing the compiled OpenEXR C++ libs. I assume the `OpenEXR` python package contains the dynamic libraries already.

**Comment by BachiLi** [comment]
This is weird...are you using https://pypi.org/project/OpenEXR/? If you look at the files there (https://pypi.org/project/OpenEXR/#files) it doesn't really contain the openexr library (it's just the Python binding).

**Comment by mworchel** [comment]
I'm using the inofficial windows package from https://www.lfd.uci.edu/~gohlke/pythonlibs/. It might be that OpenEXR was statically linked, so kind of build into the windows package. If that's not the case for linux and mac, I of course understand why it is needed as dependency.

EDIT: I need to have a look at why the windows build fails. If I figure that out, I can leave the dependencies untouched and just add OpenEXR binaries to the redner-dependencies repository.

**Comment by BachiLi** [comment]
Yeah it seems that for Windows we can just ask the users to install the openexr pip package.

**Comment by mworchel** [comment]
I managed to get the compilation of openexrpython working by fixing the compiler and linker args in `setup.py` for MSVC and adding static OpenEXR libs to the dependencies. We also need to wait for the changes I submitted to `openexrpython` upstream. `OpenEXR.cpp` is missing an include and MSVC complains about that (https://github.com/jamesbowman/openexrpython/pull/38). 

A `python setup.py install` now smoothly runs through with all the changes.

However, when I try to do an `import pyredner` in python, it says that there is not module named `redner`. When I manually copy the file `redner.cp36-win_amd64.pyd` to the `site-packages` directory it works. Shouldn't the install command take care of that or is this defined behavior?

**Comment by BachiLi** [comment]
It should -- see the code here:
https://github.com/BachiLi/redner/blob/master/setup.py#L58
https://github.com/BachiLi/redner/blob/master/setup.py#L65
Where did you find the file `redner.cp36-win_amd64.pyd`?

**Comment by mworchel** [comment]
> Where did you find the file redner.cp36-win_amd64.pyd?

When building the wheel, it is output to a temporary build directory and removed after the command finishes. I suspect setting `CMAKE_LIBRARY_OUTPUT_DIRECTORY` doesn't do what it's supposed to do.

EDIT: Got it. 
```python
if platform.system() == "Windows":
    cmake_args += ['-DCMAKE_LIBRARY_OUTPUT_DIRECTORY_{}={}'.format(cfg.upper(), extdir),
                   '-DCMAKE_RUNTIME_OUTPUT_DIRECTORY_{}={}'.format(cfg.upper(), extdir)]
```
Did the trick.

**Comment by BachiLi** [comment]
I found the same solution (
https://stackoverflow.com/questions/56514533/how-to-specify-the-output-directory-of-a-given-dll). Thanks ; )

**Comment by mworchel** [comment]
Glad it works now. I will close this issue now, thanks for your help!
